DESTDIR=

all:

.phony: install
install:
	install -D -m 644 pve-installer.css ${DESTDIR}/var/lib/pve-installer/html/pve-installer.css
	install -D -m 644 page1.htm ${DESTDIR}/var/lib/pve-installer/html/page1.htm
	install -D -m 644 country.htm ${DESTDIR}/var/lib/pve-installer/html/country.htm
	install -D -m 644 passwd.htm ${DESTDIR}/var/lib/pve-installer/html/passwd.htm
	install -D -m 644 license.htm ${DESTDIR}/var/lib/pve-installer/html/license.htm
	install -D -m 644 extract1-license.htm ${DESTDIR}/var/lib/pve-installer/html/extract1-license.htm
	install -D -m 644 extract2-rulesystem.htm ${DESTDIR}/var/lib/pve-installer/html/extract2-rulesystem.htm
	install -D -m 644 extract3-spam.htm ${DESTDIR}/var/lib/pve-installer/html/extract3-spam.htm
	install -D -m 644 extract4-virus.htm ${DESTDIR}/var/lib/pve-installer/html/extract4-virus.htm
	install -D -m 644 fail.htm ${DESTDIR}/var/lib/pve-installer/html/fail.htm
	install -D -m 644 ipconf.htm ${DESTDIR}/var/lib/pve-installer/html/ipconf.htm
	install -D -m 644 nohds.htm ${DESTDIR}/var/lib/pve-installer/html/nohds.htm
	install -D -m 644 nonics.htm ${DESTDIR}/var/lib/pve-installer/html/nonics.htm
	install -D -m 644 success.htm ${DESTDIR}/var/lib/pve-installer/html/success.htm
	install -D -m 644 plus.png ${DESTDIR}/var/lib/pve-installer/html/plus.png

.phony: clean
clean:
	rm -rf *~
